
server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /testDemo

#server:
#  port: 8084
#  servlet:
#    context-path: /testDemo
#  tomcat:
#    uri-encoding: UTF-8


spring:
  jpa:
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 1000
        min-idle: 50
        max-wait: 2000